spring:
  application:
    name: order-service
  jackson:
    default-property-inclusion: NON_NULL
  config:
    import: optional:.env[.properties]
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: ${SPRING_LIQUIBASE_DEFAULT-SCHEMA}
    url: ${SPRING_JDBC_URL}
server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE-URL}
  instance:
    prefer-ip-address: true


settings:
  taskProducer: classpath:kafka/taskProducer.xml