spring:
  application:
    name: order-service
  jackson:
    default-property-inclusion: NON_NULL
  config:
    import: optional:.env[.properties]
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: ${SPRING_JDBC_URL}
server:
  port: 8080

settings:
  taskProducer: classpath:kafka/taskProducer.xml